title: Augusto Goulart
description: This page is just an aggregation of links to some of my projects/works and shit posting.
url: https://oAGoulart.github.io
remote_theme: oAGoulart/lesta
#theme: lesta

exclude: [
  Gemfile.lock,
  lesta.gemspec,
  README.md,
  CHANGELOG.md,
  Gemfile, vendor, scripts
]
