title: Goulart
email: 3tr54eh7o@mozmail.com
author: Augusto Goulart
firstyear: 2019
description: Humane design, by humans, for humans.
baseurl: ""
url: ""
collections:
  analyses:
    output: true
    permalink: /:collection/:name
  rambles:
    output: true
    permalink: /:collection/:name
