title: Augusto Goulart
description: This page is just an aggregation of links to some of my projects/works and shit posting.
url: https://joseaugustogoulart.com
remote_theme: oAGoulart/lesta
#theme: lesta
collections:
  projects:
    output: false
permalink: /:title
plugins:
  - jekyll-seo-tag

exclude: [
  Gemfile.lock,
  lesta.gemspec,
  README.md,
  CHANGELOG.md,
  Gemfile, vendor, scripts
]
