name: Augusto Goulart
title: Augusto Goulart
description: A personal site where I can post stuff
url: "https://joseaugustogoulart.me"
contact: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%63%6F%6E%74%61%63%74%40%6A%6F%73%65%61%75%67%75%73%74%6F%67%6F%75%6C%61%72%74%2E%6D%65"
author:
  twitter: oA_Goulart
twitter: 
  username: oA_Goulart
  card: summary
facebook:
  app_id: 2869416263380091
logo: /assets/images/logo.png
social:
  name: 
  links:
    - https://twitter.com/oA_Goulart
    - https://github.com/oAGoulart
collections:
  tag:
    output: true
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/banner.png
  - scope:
      path: "_tag"
    values:
      layout: "tag"
      permalink: "/tags/:title/"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:categories/:title:output_ext
      categories: posts
plugins:
  - jekyll-seo-tag
  - jekyll-mentions
